# Generated by Django 5.0.6 on 2024-06-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_user_is_doctor_remove_user_is_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Patient', 'patient'), ('Doctor', 'doctor')], max_length=10),
        ),
    ]
