# Generated by Django 5.0.6 on 2024-06-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_doctor_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('Slot 1', '09:00 AM'), ('Slot 2', '09:30 AM'), ('Slot 3', '10:00 AM'), ('Slot 4', '10:30 AM'), ('Slot 5', '11:00 AM'), ('Slot 6', '11:30 AM'), ('Slot 7', '12:00 PM'), ('Slot 8', '12:30 PM'), ('Slot 9', '02:00 PM'), ('Slot 10', '02:30 PM'), ('Slot 11', '03:00 PM'), ('Slot 12', '03:30 PM'), ('Slot 13', '04:00 PM'), ('Slot 14', '04:30 PM'), ('Slot 15', '05:00 PM'), ('Slot 16', '05:30 PM')], max_length=10)),
                ('appointment_desc', models.CharField(max_length=100, unique=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='Account.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='Account.patient')),
            ],
        ),
    ]
